from typing import Protocol

from ai_comp.database.models import RegistrySnapshot
from ai_comp.domain.exams import ConductingBody, Exam, PaperCategory
from ai_comp.domain.sources import SourceRecord
from ai_comp.domain.verification import SourceVerification


class RepositoryError(RuntimeError):
    """Base error for persistence implementations."""


class RegistryRepository(Protocol):
    """Storage contract.

    Phase 1 keeps the interface database-agnostic. A PostgreSQL implementation
    can satisfy this protocol later without changing the domain layer.
    """

    def save_body(self, body: ConductingBody) -> None: ...
    def save_exam(self, exam: Exam) -> None: ...
    def save_category(self, category: PaperCategory) -> None: ...
    def save_source(self, source: SourceRecord) -> None: ...
    def save_verification(self, verification: SourceVerification) -> None: ...

    def get_body(self, body_id: str) -> ConductingBody | None: ...
    def get_exam(self, exam_id: str) -> Exam | None: ...
    def get_category(self, category_id: str) -> PaperCategory | None: ...
    def get_source(self, source_id: str) -> SourceRecord | None: ...
    def get_verifications(self, source_id: str) -> tuple[SourceVerification, ...]: ...

    def snapshot(self) -> RegistrySnapshot: ...
