from typing import Protocol

from ai_comp.database.models import RegistrySnapshot
from ai_comp.domain.exams import ConductingBody, Exam, PaperCategory
from ai_comp.domain.questions import AnswerKeyEntry, QuestionCandidate
from ai_comp.domain.sources import SourceRecord
from ai_comp.domain.verification import SourceVerification
from ai_comp.domain.matching import QuestionMatch
from ai_comp.research.paper import FetchedDocument, PaperCandidate
from ai_comp.research.processing import NormalizedDocument


class RepositoryError(RuntimeError):
    """Base error for persistence implementations."""


class RegistryRepository(Protocol):
    """Database-neutral registry storage contract."""

    def save_body(self, body: ConductingBody) -> None: ...
    def save_exam(self, exam: Exam) -> None: ...
    def save_category(self, category: PaperCategory) -> None: ...
    def save_source(self, source: SourceRecord) -> None: ...
    def save_verification(self, verification: SourceVerification) -> None: ...

    def get_body(self, body_id: str) -> ConductingBody | None: ...
    def get_exam(self, exam_id: str) -> Exam | None: ...
    def get_category(self, category_id: str) -> PaperCategory | None: ...
    def get_source(self, source_id: str) -> SourceRecord | None: ...
    def get_verifications(self, source_id: str) -> tuple[SourceVerification, ...]: ...

    def snapshot(self) -> RegistrySnapshot: ...


class QuestionRepository(Protocol):
    """Persistence contract for extracted question candidates."""

    def save(self, question: QuestionCandidate) -> None: ...
    def get(self, question_id: str) -> QuestionCandidate | None: ...
    def get_for_document(self, document_id: str) -> tuple[QuestionCandidate, ...]: ...


class AnswerKeyRepository(Protocol):
    """Persistence contract for source-observed answer-key entries."""

    def save_many(
        self,
        document_id: str,
        entries: tuple[AnswerKeyEntry, ...],
    ) -> None: ...

    def get_for_document(self, document_id: str) -> tuple[AnswerKeyEntry, ...]: ...


class MatchRepository(Protocol):
    """Persistence contract for explicit question relationships."""

    def save(self, match: QuestionMatch) -> None: ...
    def get_for_question(self, question_id: str) -> tuple[QuestionMatch, ...]: ...


class ResearchRepository(Protocol):
    """Persistence contract for research and document metadata layers."""

    def save_candidate(self, candidate: PaperCandidate) -> None: ...
    def save_document(self, document: FetchedDocument) -> None: ...
    def save_normalized_document(self, document: NormalizedDocument) -> None: ...
